### ISSUE TITLE
`get_value_counts` doesn't work for multiclass learning

### ISSUE THREAD

**Issue by ben-heil** [greenelab/whistl#18]
I think this can be fixed easily by getting rid of the unnecessary `int` casting in `get_value_counts`, but the encoding that showed up when I was debugging the issue seems to not be one-hot either.

tensor([[0., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]], dtype=torch.float64)
Traceback (most recent call last):
  File "classifier.py", line 591, in <module>
    results = train_with_erm(classifier, train_loader, tune_loader, args.num_epochs, logger)
  File "classifier.py", line 242, in train_with_erm
    class_weights = util.get_class_weights(train_loader)
  File "/home/ben/repos/whistl/whistl/util.py", line 316, in get_class_weights
    value_counts, total = get_value_counts(train_loader)
  File "/home/ben/repos/whistl/whistl/util.py", line 349, in get_value_counts
    if int(label) not in value_counts:
ValueError: only one element tensors can be converted to Python scalars

**Comment by ben-heil** [comment]
`get_value_counts` is also broken in erm/irm

**Comment by ben-heil** [comment]
Fixed
